first draft of section1 for data science pipelines
RedHatQuickCourses/rhods-pipelines pull request #4
Opened 2023-11-17 09:57 UTC by codrinbucur

first draft of section1 for data science pipelines. please review!

2023-11-17 10:23 UTC, rsriniva approved these changes
Approving for now. Let's merge this

2023-11-17 10:25 UTC, rsriniva commented
@mamurak - Please review Codrin's introduction to Pipelines lecture in this PR. The HTML rendering is broken because this PR was created from a fork. Please review raw asciidoc file in this PR

2023-11-17 10:51 UTC, jramcast reviewed
Good intro section! Make sure you fix the image paths.

2023-11-17 10:51 UTC, jramcast commented on modules/chapter1/pages/section1.adoc
> +image::../images/dsps-main.png[Data Science Pipelines Menu / Main View]
Antora is not rendering the images cause the paths are incorrect. Remove the `../images` portion in this image and the remaining ones.


file:///Users/jairamir/courses/rhods-pipelines/build/site/rhods-pipelines/1.33/chapter1/section1.html
<img width="707" alt="image" src="https://github.com/RedHatQuickCourses/rhods-pipelines/assets/675470/05658e69-ec7a-42db-a336-01c05c13c900">



```suggestion
image::dsps-main.png[Data Science Pipelines Menu / Main View]
```

2023-11-20 15:50 UTC, mamurak reviewed
Added two minor comments. Looks good to me overall.

2023-11-20 15:50 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +* *OpenShift Pipelines (based on Tekton)* - It executes each step in the pipeline as an individual container / job and ensures that each containers gets allocated the resources (GPU, CPU, memory) con
```suggestion
* *OpenShift Pipelines (based on Tekton)* - It executes each step in the pipeline as an individual container and ensures that each container gets allocated the resources (GPU, CPU, memory) configured/requested by data scientists in Elyra (or via Kubeflow SDK), as long as they are available in the OpenShift cluster.
```

Technically, Tekton is based on pods, not jobs.

2023-11-20 15:50 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +* *OpenShift GitOps with ArgoCD for AI/ML flows* - While not part of the OpenShift AI but rather as part of OpenShift, it is worth mentioning that once ML models are created, GitOps can be leveraged
```suggestion
* *OpenShift GitOps with ArgoCD for automated model deployments* - While not part of the OpenShift AI but rather as part of OpenShift, it is worth mentioning that once ML models are created, GitOps can be leveraged to push them to other OpenShift instances (including OpenShift Edge devices) for being hosted on model servers for inference and/or embedded in intelligent apps.
```

2023-11-20 15:52 UTC, mamurak requested changes
Highlighted necessary changes for image rendering.

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/dsps-main.png[Data Science Pipelines Menu / Main View]
```suggestion
image::dsps-main.png[Data Science Pipelines Menu / Main View]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/dsps-runs.png[Data Science Pipelines Runs]
```suggestion
image::dsps-runs.png[Data Science Pipelines Runs]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/dsps-in-ds-project.png[Data Science Pipelines view within a Data Science Project]
```suggestion
image::dsps-in-ds-project.png[Data Science Pipelines view within a Data Science Project]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/dsp-run-in-ocp-pipelines.png[OpenShift Pipeline executing a Data Science Pipeline]
```suggestion
image::dsp-run-in-ocp-pipelines.png[OpenShift Pipeline executing a Data Science Pipeline]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/elyra-pipeline-offline-scoring.png[An Offline Scoring pipeline in Elyra]
```suggestion
image::elyra-pipeline-offline-scoring.png[An Offline Scoring pipeline in Elyra]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/elyra-pipeline-model-training.png[A Model Training pipeline in Elyra]
```suggestion
image::elyra-pipeline-model-training.png[A Model Training pipeline in Elyra]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/elyra-pipeline-step-config-with-gpu.png[Configuring GPUs and other resources for an Elyra pipeline step]
```suggestion
image::elyra-pipeline-step-config-with-gpu.png[Configuring GPUs and other resources for an Elyra pipeline step]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/elyra-pipeline-running.png[Starting an Elyra pipeline]
```suggestion
image::elyra-pipeline-running.png[Starting an Elyra pipeline]
```

2023-11-20 15:52 UTC, mamurak commented on modules/chapter1/pages/section1.adoc
> +image::../images/elyra-pipeline-job-started.png[Details of a started Elyra pipeline]
```suggestion
image::elyra-pipeline-job-started.png[Details of a started Elyra pipeline]
```

2023-11-22 07:24 UTC, codrinbucur commented
Committed all suggestions from Max and Jaime

2023-11-22 11:38 UTC, merged